# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjkIsJTuGjXgRBK9ikQFwAbzW69LcPr9
"""

import numpy as np

"""#Split"""

data = np.load("pendulum_dataset.npz")

print("Available keys:", data.files)  # Lists all keys in the archive
traj_IDs = data["traj_ID"]
unique_traj = np.unique(traj_IDs)

np.random.seed(42)
np.random.shuffle(unique_traj)

n_train = int(0.8 * len(unique_traj))
train_traj = unique_traj[:n_train]  # training dataset contain 80% of all the data
test_traj = unique_traj[n_train:]   # test dataset contain 20% of all the data

train_idx = np.isin(traj_IDs, train_traj)
test_idx = np.isin(traj_IDs, test_traj)

np.savez(
    "splits.npz",
    train_idx=train_idx,
    test_idx=test_idx
)